### ISSUE TITLE
NIST Password checklist below password text field

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#1046]
Example:
- [ ] Password strength
- [ ] Can't contain your name or email address
- [ ] At least 8 characters
- [ ] Contains a number or symbol
