### ISSUE TITLE
UX/UI Design website, onboardings, guest/host dashboards, search, book, messaging, pay, review, API

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#11]
**[UX/UI Design website](https://github.com/domits1/Domits/issues/11 )**
**[UX/UI Design app](https://github.com/domits1/Domits/issues/64)**
**[UX/UI Design presentatie](https://docs.google.com/presentation/d/1HZIUjdjWIfQH4EKo-RH19MqMNohugzt_87Cf9SL5ToI)**

**Improve UX/UI research, discover & define phase**
- Desk research, [Persona's](https://bookdomits.com/user-personas-hospitality-travel-vacation-rental-companies/), [Customer journeys](https://bookdomits.com/hospitality-customer-journeys-guest-host/), Mindmapping, Questionnaires, [Value proposition canvas](https://bookdomits.com/value-proposition-canvas-vpc-vacation-rental-enterprises/), User needs, Storyboarding, Service blueprints, [Business model canvas](https://bookdomits.com/domits/), [Requirements analysis](https://github.com/domits1/Domits/issues/1226), Data driven design

**Improve UX/UI Develop, Deliver, Test & Publish**
- Persona based walkthroughs, Sketching, wireframing, stylesheets, flow diagrams host/guest experience, LoFi, HiFi, Usability testing, Multi language / Multi currency

**v1 UX/UI Design System Architecture** 
- [x] [v1 Website pages](https://github.com/domits1/Domits/issues/162)
- [x] [Website booking engine guests](https://github.com/domits1/Domits/issues/619)
- [x] [v1 Website guest dashboard](https://github.com/domits1/Domits/issues/142)
- [x] v1 Website host onboarding
- [x] [v1 Website host dashboard](https://github.com/domits1/Domits/issues/149)
- [x] v1 [Website Booking & availability Calendar](https://github.com/domits1/Domits/issues/36)
- [x] [v1 Website Help for guests/hosts](https://github.com/domits1/Domits/milestone/18)
- [x] v1 Website Internal/External IAM

**v2 UX/UI Design System Architecture** 
- [ ] v2 UX/UI Design Web Pages
- [x] v2 UX/UI Design Host Onboarding
- [x] v2 UX/UI Design Property Management System
- [x] v2 UX/UI Design Calendar & Pricing
- [ ] v2 UX/UI Design Central Reservation System
- [x] v2 UX/UI Design Messaging Unified Inbox with AI
- [ ] v2 UX/UI Design Revenue Management System
- [x] v2 UX/UI Design Tasks for Maintenance & Housekeeping
- [ ] v2 UX/UI Design Guest Experience (Booking Engine & Dashboard)
- [ ] v2 UX/UI Design Host Finance
- [ ] v2 UX/UI Design Channel Management System
- [ ] v2 UX/UI Design Marketplace for integrations & Open API
- [ ] v2 UX/UI Design Review System

----
Later
**Website admin panel tabs**
- [ ] Manage admin, guests, hosts, enterprise
- [ ] Manage documents, services, help, locations, map, fee, bookings, ratings, messages, refferals, payouts, wallets, promos, app version, settings, web/app language, app 

Iconpack website for amenities -> https://www.flaticon.com/authors/those_icons/lineal?author_id=216&type=standard
Iconpack voor UI UX -> Figma Untitled Icons Free edition

**Comment by HisjaamB** [comment]
Zoals te zien, de 1e versies van de Host dashboards. Widget layout ligt er al. Inhoudelijk widget invulling laat ik dit aan de devs over na wat brainstormen. Vervolgens de focus op een nieuw settings layout. 

Consistentie met de guest is behouden. Echter is corporate blauw de main colour op alle host pagina's/schermen die er ontworpen worden. Hieruit feedback van Tim en Gianni ter bevestiging dat de kleur mooi en clean oogt voor de zakelijke Domits functionaliteiten.

![Host Dashboard Landing](https://github.com/domits1/Domits/assets/144668782/01199210-ff29-4259-ab10-e9927acf9a03)
![Host Listings](https://github.com/domits1/Domits/assets/144668782/7a4fce8c-b134-4c49-8c46-1008a200ca61)
![Host Payments](https://github.com/domits1/Domits/assets/144668782/1a90fbe7-5402-4b5b-8f8f-d0d4e08dbd1e)
![Host Settings](https://github.com/domits1/Domits/assets/144668782/8d49c804-dc10-4296-9dd1-0de2a5639d85)

**Comment by roberthopman** [comment]
Misschien 2 punten om over na te denken:
- Bij de settings pagina zie ik 4 edit knoppen, wellicht eenvoudiger en handiger voor ontwikkeling ook om daar 1 algemene update knop van te maken. 
- logo in de footer is misschien overkill

**Comment by HisjaamB** [comment]
@roberthopman 
Zie hier een nieuwe optie voor de settings pagina: 
![image](https://github.com/domits1/Domits/assets/144668782/987c9d0d-11c6-4376-a2f2-fb55ddc60787)

Over de footer: Volgende week komt er een minimalized Domits footer voor de pagina's waarbij dit overkill wordt. Ben het met je eens.

**Comment by HisjaamB** [comment]
Eerste versie van de Host step 1 na het invullen van de 3 stappen op become a host is af. De volgende layout van simpelheid wil ik aanhouden. Verdere uitleg en argumentatie volgt na het ontwikkelen van de opvolgende stappen.
![image](https://github.com/domits1/Domits/assets/144668782/5d10a066-8162-4991-826e-e842bdec3cbd)

**Comment by HisjaamB** [comment]
Een simpele in dezelfde stijl als de andere statische pagina's, help pagina. Content wordt nog aangevuld, voor nu is het een klik en expand idee. 

![Desktop - Help](https://github.com/domits1/Domits/assets/144668782/5edd3ceb-c1a7-4c2e-bf6b-ceb199728c24)

**Comment by HisjaamB** [comment]
Release page is nu klaar voor dev. O.b.v. de standaard empty page template.

![Release](https://github.com/domits1/Domits/assets/144668782/47f820d6-08f9-47fa-bf32-804683f65433)

**Comment by HisjaamB** [comment]
Statische pagina's zijn afgemaakt als landing page voor de categories. Hierbij 3 pages en 2 varianten. Waarvan de 2e variant voor wat exclusiever aanbod gebruikt kan worden en variatie 1 als regulier.

![Desktop - 65](https://github.com/domits1/Domits/assets/144668782/af785011-af25-4899-81a5-1a754613e6f0)
![Desktop - 66](https://github.com/domits1/Domits/assets/144668782/3118cacd-6acc-43cd-876e-113f17f17ab6)
![Desktop - 67](https://github.com/domits1/Domits/assets/144668782/2aa43341-e3d9-44ad-857c-8527ff44ce57)

**Comment by roberthopman** [comment]
Hi @HisjaamB 

Algemene observatie: bedenk even of deze font families die je gebruikt, de juiste zijn. Hoe heb je dit momenteel bedacht?

Verdere observaties:

404 pagina: 
- mag iets van droge humor bevatten (vrij in te vullen)
- 500 pagina mag ook iets hebben en met een ander creatief idee (vrij in te vullen)

Settingspagina: 
- probeer de 'attribute values' van de diverse onderdelen te tonen, in de normale 'value + action buttons', nu lijken de 'Change...' allemaal geen values te tonen (wat zijn settings) maar juist wel actionable en clickable. 
- Ik zie paars. Is dat besloten als tweede kleur?
- ivm paars: Kan jij nog eens de figma link delen?

Index pagina:
- font size misschien iets groter hier en daar
- de button 'All accommodations' misschien minder opvallend.
- (c) 2023 is nu 2024. 

Host step 1:
- go back and proceed buttons andere basis kleuren geven, de shade is wel goed bij back.

Heb jij zelf nog vragen?

**Comment by HisjaamB** [comment]
2 versies van de Travel Innovation Lab - static landing page  - zijn af. Er kan een keus gemaakt worden uit deze variaties. Vanuit design gaat mijn voorkeur uit naar de verticale kolom variant waar dan tekst in komt. De blokken variant vind ik iets te kinderachtig ogen voor Domits. 

![Desktop - 68](https://github.com/domits1/Domits/assets/144668782/b1180370-c9ee-4795-9326-fa4998b901db)
![Desktop - 69](https://github.com/domits1/Domits/assets/144668782/58e90e84-88da-4806-97f7-948d0a123cd5)

**Comment by stefanhopman1** [comment]
Variant 1 is prima

**Comment by HisjaamB** [comment]
De nieuwe versies van de statische schermen (Why Domits en About Domits) zijn klaar. 

Er is gebruik gemaakt van een tekst, kolom en icoon structuur voor het minimalisme. Eventuele zou hier ergens een leuk pictogram of afbeelding bij kunnen maar de 1e versie heeft aan deze schermen voldoende. 

![Desktop - 70](https://github.com/domits1/Domits/assets/144668782/c81348df-e694-4f2a-a14f-d525f4606193)
![Desktop - 71](https://github.com/domits1/Domits/assets/144668782/3fdbd82c-7ff2-4e38-9ffd-e345d12f6abc)

**Comment by HisjaamB** [comment]
Vanuit User Experience en verwachtingsmanagement voor de gebruiker heb ik de voglende designkeuze gemaakt:

In plaats van een ouderwets maar klassieke loading scherm na het selecteren van filters en het klikken op de zoek knop in de search bar op de home page (accommoverview) kies ik voor een **skeleton loader** (zie afbeelding).

De skeleton loader heeft als voordelen:
- Ze lijken sneller en gebruiksvriendelijker te zijn. 
- Verbeterde waargenomen prestaties zorgen voor zowel een goede UX als helpen bij het verhogen van de conversieratio.
- Het probleem met spinners/laders is dat we geen idee hebben wat er wordt geladen of hoe lang het zal duren.
- Het gebruik van spinners/laders creëert een periode van onzekerheid voor de gebruiker, aangezien de laadtijd onbekend is.
- Vvestigen de aandacht van de gebruiker op de voortgang in plaats van op de wachttijd.
- Het creëert een illusie van snelheid en korte laadtijd

![image](https://github.com/domits1/Domits/assets/144668782/9d9aa263-43bf-4502-91b1-001eb4699ced)

**Comment by roberthopman** [comment]
Goed idee. Wellicht ook niet onverstandig om te beschrijven wat de nadelen van de skeleton loader zijn?
