### ISSUE TITLE
Roadmap Domits App

### ISSUE THREAD

**Issue by Muubii** [domits1/Domits#1438]
Warning:
- [x] #1439
- [x] #1440

Bugs: 
- [x] QR Page

Errors:
- [x] Error VieuwPropTypes
- [x] NAVIGATE with payload {"name":emailSettings was not handled by any navigator}
- [x] NAVIGATE with payload {"name":Password was not handled by any navigator}
- [x] Error not open URL ; Scan a QR code 
- [x] Search bar error 

Hardcode:
- [x] Settings Host/Guest
- [x] Payment page
- [x] Bookings homepage
- [x] Confirm and pay

Finished but not totally finished it:
- [x] Hostonboarding
- [x] Profile page Host/Guest
- [x] Guest revieuw
- [x] Help and feedback page Host/Guest -dashboard
- [x] Both Dashboards set Name of user

Pages that can be left out:
- [x] Revenue toool
- [x] Payments guestdashboard
- [x] Pay Tab Home
- [x] Pocket Home can be replaced with settings
- [x] All the way down homepage "go to host dashboar" and "Guest" can be removed from here.
