### ISSUE TITLE
App: Main issue (startingpoint)

### ISSUE THREAD

**Issue by Timmhart** [domits1/Domits#194]
- [ ] https://github.com/domits1/Domits/issues/1316
- [ ] [App: Host onboarding + dashboard](https://github.com/domits1/Domits/milestone/25) 
- [ ] [App: Guest booking engine + dashboard](https://github.com/domits1/Domits/milestone/26) 
- [ ] [App: Account & user profile management](https://github.com/domits1/Domits/milestone/27) 
- [ ] [App: Search & discoverability](https://github.com/domits1/Domits/milestone/28) 
- [ ] [App: Finance](https://github.com/domits1/Domits/milestone/29) 
- [ ] [App: Calendar & prices](https://github.com/domits1/Domits/milestone/33) 
- [ ] [App: Messages](https://github.com/domits1/Domits/milestone/31) 
- [ ] [App: Reviews](https://github.com/domits1/Domits/milestone/30) 
- [ ] [App: Help](https://github.com/domits1/Domits/milestone/32) 
- [ ] -
- [ ] [App: Navigation: Main](https://github.com/domits1/Domits/issues/229) 
- [ ] [App: Navigation: Home tab](https://github.com/domits1/Domits/issues/40) 
- [ ] [App: Navigation: Messaging tab](https://github.com/domits1/Domits/issues/41)
- [ ] [App: Navigation: Account tab](https://github.com/domits1/Domits/issues/42) 
- [ ] [Research:  React native cli setup](https://reactnative.dev/docs/environment-setup?guide=native)

Please add your research (short findings) here in the comments.
Place all other (bigger) findings in the designated wiki page.

**Comment by Timmhart** [comment]
@kacperfl Please read the description.

**Comment by Timmhart** [comment]
[This](https://aws.amazon.com/device-farm/) could be used for testing during development if needed. 
For the free tier we only have 1.000 device minutes free.
