### ISSUE TITLE
Website: admin panel frontend styling & functional

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#20]
Admin panel Functional & frontend styling
- [ ] Dashboard
- [ ] Manage admin
- [ ] Manage guests
- [ ] Manage hosts
- [ ] Manage company 
- [ ] Manage documents 
- [ ] Manage services
- [ ] Manage help
- [ ] Manage locations
- [ ] Manage map
- [ ] Manage fare
- [ ] Manage requests
- [ ] Manage bookings
- [ ] Manage ratings
- [ ] Manage messages
- [ ] Manage referrals
- [ ] Manage payouts
- [ ] Manage wallet & promos
- [ ] Manage app version
- [ ] Manage settings
- [ ] Manage web language
- [ ] Manage app language

**Comment by Timmhart** [comment]
See #977
