### ISSUE TITLE
App: Navigation: Home tab

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#40]
- [ ] [App: Home tab: Scan](https://github.com/domits1/Domits/issues/55)
- [ ] [App: Home tab: Pay](https://github.com/domits1/Domits/issues/571)
- [ ] [App: Home tab: Bookings](https://github.com/domits1/Domits/issues/57)
- [ ] [App: Home tab: Wallet](https://github.com/domits1/Domits/issues/58)
- [ ] [App: Home tab: AppCenter](https://github.com/domits1/Domits/issues/572)
- [ ] [App: Home tab: Notifications](https://github.com/domits1/Domits/issues/43)
