### ISSUE TITLE
Prepare submission iOS App in App Store & Android app in Play Store

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#45]
**Checklist - iOS App-store**
- [ ] https://github.com/domits1/Domits/issues/1056
- [x] https://github.com/domits1/Domits/issues/1299
- [x] Create Developer account (€99,- p.y.) Apple Developer
- [x] App store connect https://appstoreconnect.apple.com/login
- [x] TestFlight on App Store
- [x] Assemble App Store information
- [x] Create a Bundle Identifier
- [x] Create a Certificate Signing Request
- [x] Create an App Store Production Certificate
- [x] Create a Production Provisioning Profile 
- [x] Create an App Store listing
- [ ] Create a Release Build
- [ ] Fill in the Version Information
- [x] Submit Version for Review
- [ ] Release
- [ ] https://github.com/domits1/Domits/issues/1056
- [ ] How To Submit An App To The App Store (The Right Way) https://clearbridgemobile.com/how-to-submit-an-app-to-the-app-store/

**Checklist - iOS listing**

- [x] - App name: Domits
- [x] - App description: List, discover and book accommodations
- [x] - Keywords: travel tech
- [x] - Category
- [x] - Pricing: Free download.
- [x] - High resolution icon
- [ ] - Screenshots
- [ ] - App Preview Video
- [ ] - App review contact details
- [ ] - Availability
- [ ] - SKU number
- [x] - Marketing URL: https://domits.com/
- [x] - Support URL: https://domits.com/contact
- [ ] - Terms & conditions: https://www.domits.com/terms/
- [ ] - Privacy policy: https://www.domits.com/policy/
- [ ] - Disclaimer: https://www.domits.com/disclaimers/
- [ ] - End User License Agreement: 
- [ ] - Copyright information: 

**Checklist - Play Store**

- [ ] https://github.com/domits1/Domits/issues/1225
- [ ] Google Play Developer account (one-time fee [$25)
- [ ] (Link developer account with google wallet merchant account)
- [ ] APK
Other information for the Play Store see above at iOS checklists
