### ISSUE TITLE
Host: Account Settings: Team - Team members, roles, account protection and shared resources

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#513]
##  Feature Summary
To allow users with different access levels to manage properties, we want to allow hosts to invite team members. This will be done within the account settings. Team members will be assigned a predefined role, giving them certain permissions within the hosts PMS.

- [x] #2390 
- [ ] #3300 

___

### Designs for this tab are shared in the pinned comment of this issue!
---

### Frontend implementation 

***Primary team members***

Shows an overview of main team members (hosts, co host etc) 

- [x] Primary host header
- [x] PFP, Name, Role, email and phone number

Within the Account settings: Team, an overview is shown showing all current teammembers. There is also an option to invite new team members.  This is shown in a table with the following collumns:

- [x] Team members header
- [x] Name
- [x] Role
- [x] Email
- [x]  Properties (which properties does this team member relate to? 
- [ ] Member status (active , suspended etc)

#### Inviting new teammembers

To invite new teammembers, a green **invite members** button is present. When pressed, you can enter an email adress to invite a new teammember

- [x] An in window screen allows filling in an email
- [x] When send is pressed, an invitation email is sent to the team member

**Comment by Ryan-Reddy** [comment]
Huidge roles in Cognito:

![Image](https://github.com/user-attachments/assets/8c34314b-6821-45d9-9c66-a7471a0784a0)

Huidige methods in Lambda die "User" bevatten:
![Image](https://github.com/user-attachments/assets/4a690e3e-6d2e-4140-a05a-f14c8099c857)

Voorbeeld updateEmail:
https://eu-north-1.console.aws.amazon.com/lambda/home?region=eu-north-1#/functions/confirmEmailChange?tab=code


Lambda UserVerification:
https://media.discordapp.net/attachments/1338070849634172949/1347177436193886218/image.png?ex=67cae042&is=67c98ec2&hm=6a79c4a6b6fc8c1238dedee68367803bdd126fff28783ef07b8bd14d30c4c0d5&=&format=webp&quality=lossless&width=1706&height=905

[Manage User sessions amplify documentations](https://docs.amplify.aws/react-native/build-a-backend/auth/connect-your-frontend/manage-user-sessions/)

**Comment by vanheerwaardenchiel-bit** [comment]
<img width="1526" height="1797" alt="Image" src="https://github.com/user-attachments/assets/df543311-be51-4964-a985-fb29fd9cf380" />
