### ISSUE TITLE
Website: Host dashboard (Settings tab)

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#589]
## 🚀 Feature Summary

v1 Host Settings
- [x] https://github.com/domits1/Domits/issues/1766

v2 Host Settings

**Category: Personal settings**
- [ ] settings/user Personal Data. Include https://github.com/domits1/Domits/issues/2274
- [ ] settings/communication-preferences Communication Preferences (e-mails, sms-messages, push-notifications)

**Category: Account Settings**
- [ ] settings/account Company (Account data, account status, public information, payouts, legal entity and more)
- [ ] settings/team Team (Team members, roles, account protection and shared resources) #2390 
- [ ] settings/plans Your Rate Plans (Manage how you pay for Domits-services)
- [ ] settings/compliance Compliance (Documents) #761

**Comment by stefanhopman1** [comment]
v2
